import { StyleSheet } from "react-native";

export const invitationManagementStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F8FAFC" },
  contentCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 18,
    gap: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 1,
  },
  toggleButton: {
    borderRadius: 8,
    backgroundColor: "#E2E8F0",
    paddingVertical: 14,
    alignItems: "center",
  },
  toggleButtonText: {
    color: "#0F172A",
    fontWeight: "700",
  },
  formWrap: { gap: 12 },
  filterCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 1,
    gap: 12,
  },
  filterToggle: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  filterToggleTextWrap: { flex: 1, gap: 4 },
  filterToggleTitle: {
    color: "#0F172A",
    fontWeight: "700",
  },
  filterToggleSummary: {
    color: "#64748B",
    lineHeight: 18,
  },
  filterToggleArrow: {
    color: "#2563EB",
    fontWeight: "700",
  },
  filterFields: { gap: 12 },
  listCard: {
    backgroundColor: "white",
    borderRadius: 12,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 1,
  },
  emptyCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 1,
  },
  emptyText: {
    color: "#64748B",
    lineHeight: 20,
  },
  paginationRow: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  pageButton: {
    minWidth: 88,
    borderRadius: 8,
    backgroundColor: "#E2E8F0",
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: "center",
  },
  pageButtonDisabled: { opacity: 0.45 },
  pageButtonText: {
    color: "#0F172A",
    fontWeight: "700",
  },
  pageText: {
    color: "#475569",
    fontWeight: "600",
  },
});
