import { StyleSheet } from "react-native";

export const meStyles = StyleSheet.create({
  screen: {
    width: "100%",
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  subtitle: {
    color: "#64748B",
    fontWeight: "400",
  },
  profileCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 1,
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: "#DBEAFE",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    color: "#2563EB",
    fontSize: 22,
    fontWeight: "700",
  },
  profileMeta: {
    flex: 1,
    gap: 4,
  },
  profileName: { color: "#0F172A" },
  profileEmail: { color: "#64748B" },
  menuCard: {
    backgroundColor: "white",
    borderRadius: 12,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 1,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    gap: 12,
  },
  menuItemLast: { borderBottomWidth: 0 },
  menuText: { flex: 1, gap: 4 },
  menuTitle: {
    color: "#0F172A",
    fontWeight: "700",
    fontSize: 15,
  },
  menuDescription: {
    color: "#64748B",
    lineHeight: 20,
  },
  menuArrow: {
    color: "#94A3B8",
    fontSize: 24,
    fontWeight: "600",
  },
  emptyCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 20,
    gap: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 1,
  },
  emptyText: {
    color: "#64748B",
    lineHeight: 22,
  },
  loginButton: {
    backgroundColor: "#3C83F6",
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 4,
  },
  loginButtonText: {
    color: "white",
    fontWeight: "700",
  },
  logoutButton: {
    width: "100%",
    padding: 16,
    borderRadius: 8,
    backgroundColor: "#EF4444",
  },
  logoutButtonText: {
    color: "white",
    width: "100%",
    textAlign: "center",
    fontWeight: "700",
  },
});
