import { StyleSheet } from "react-native";

export const profileStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F8FAFC" },
  profileCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 1,
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: "#DBEAFE",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    color: "#2563EB",
    fontSize: 22,
    fontWeight: "700",
  },
  profileMeta: {
    flex: 1,
    gap: 4,
  },
  profileName: { color: "#0F172A" },
  profileEmail: { color: "#64748B" },
  infoCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 20,
    gap: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 1,
  },
  fieldRow: { gap: 4 },
  label: {
    color: "#64748B",
    fontWeight: "600",
  },
  value: { color: "#0F172A" },
  errorText: {
    color: "#DC2626",
    lineHeight: 20,
  },
  primaryButton: {
    width: "100%",
    padding: 16,
    borderRadius: 8,
    backgroundColor: "#3C83F6",
  },
  primaryButtonText: {
    color: "white",
    width: "100%",
    textAlign: "center",
    fontWeight: "700",
  },
});
